/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_stun_auth_cred_data_static_cred {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_stun_auth_cred_data_static_cred(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_stun_auth_cred_data_static_cred obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pj_stun_auth_cred_data_static_cred(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setRealm(pj_str_t value) {
    pjsuaJNI.pj_stun_auth_cred_data_static_cred_realm_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getRealm() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_static_cred_realm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setUsername(pj_str_t value) {
    pjsuaJNI.pj_stun_auth_cred_data_static_cred_username_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getUsername() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_static_cred_username_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setData_type(pj_stun_passwd_type value) {
    pjsuaJNI.pj_stun_auth_cred_data_static_cred_data_type_set(swigCPtr, this, value.swigValue());
  }

  public pj_stun_passwd_type getData_type() {
    return pj_stun_passwd_type.swigToEnum(pjsuaJNI.pj_stun_auth_cred_data_static_cred_data_type_get(swigCPtr, this));
  }

  public void setData(pj_str_t value) {
    pjsuaJNI.pj_stun_auth_cred_data_static_cred_data_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getData() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_static_cred_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setNonce(pj_str_t value) {
    pjsuaJNI.pj_stun_auth_cred_data_static_cred_nonce_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getNonce() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_static_cred_nonce_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public pj_stun_auth_cred_data_static_cred() {
    this(pjsuaJNI.new_pj_stun_auth_cred_data_static_cred(), true);
  }

}
