/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pj_stun_passwd_type {
  PJ_STUN_PASSWD_PLAIN(pjsuaJNI.PJ_STUN_PASSWD_PLAIN_get()),
  PJ_STUN_PASSWD_HASHED(pjsuaJNI.PJ_STUN_PASSWD_HASHED_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pj_stun_passwd_type swigToEnum(int swigValue) {
    pj_stun_passwd_type[] swigValues = pj_stun_passwd_type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pj_stun_passwd_type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pj_stun_passwd_type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pj_stun_passwd_type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pj_stun_passwd_type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pj_stun_passwd_type(pj_stun_passwd_type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

