/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_stun_auth_cred_data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_stun_auth_cred_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_stun_auth_cred_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pj_stun_auth_cred_data(swigCPtr);
    }
    swigCPtr = 0;
  }

  public pj_stun_auth_cred_data_dyn_cred getDyn_cred() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_stun_auth_cred_data_dyn_cred(cPtr, false);
  }

  public pj_stun_auth_cred_data_static_cred getStatic_cred() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_static_cred_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_stun_auth_cred_data_static_cred(cPtr, false);
  }

  public pj_stun_auth_cred_data() {
    this(pjsuaJNI.new_pj_stun_auth_cred_data(), true);
  }

}
