/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pjmedia_format_id {
  PJMEDIA_FORMAT_L16(pjsuaJNI.PJMEDIA_FORMAT_L16_get()),
  PJMEDIA_FORMAT_PCM(pjsuaJNI.PJMEDIA_FORMAT_PCM_get()),
  PJMEDIA_FORMAT_PCMA(pjsuaJNI.PJMEDIA_FORMAT_PCMA_get()),
  PJMEDIA_FORMAT_ALAW(pjsuaJNI.PJMEDIA_FORMAT_ALAW_get()),
  PJMEDIA_FORMAT_PCMU(pjsuaJNI.PJMEDIA_FORMAT_PCMU_get()),
  PJMEDIA_FORMAT_ULAW(pjsuaJNI.PJMEDIA_FORMAT_ULAW_get()),
  PJMEDIA_FORMAT_AMR(pjsuaJNI.PJMEDIA_FORMAT_AMR_get()),
  PJMEDIA_FORMAT_G729(pjsuaJNI.PJMEDIA_FORMAT_G729_get()),
  PJMEDIA_FORMAT_ILBC(pjsuaJNI.PJMEDIA_FORMAT_ILBC_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pjmedia_format_id swigToEnum(int swigValue) {
    pjmedia_format_id[] swigValues = pjmedia_format_id.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjmedia_format_id swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjmedia_format_id.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjmedia_format_id() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjmedia_format_id(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjmedia_format_id(pjmedia_format_id swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

