/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_stun_auth_cred {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_stun_auth_cred(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_stun_auth_cred obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pj_stun_auth_cred(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setType(pj_stun_auth_cred_type value) {
    pjsuaJNI.pj_stun_auth_cred_type_set(swigCPtr, this, value.swigValue());
  }

  public pj_stun_auth_cred_type getType() {
    return pj_stun_auth_cred_type.swigToEnum(pjsuaJNI.pj_stun_auth_cred_type_get(swigCPtr, this));
  }

  public pj_stun_auth_cred_data getData() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_stun_auth_cred_data(cPtr, false);
  }

  public pj_stun_auth_cred() {
    this(pjsuaJNI.new_pj_stun_auth_cred(), true);
  }

}
