/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_stun_auth_cred_data_dyn_cred {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_stun_auth_cred_data_dyn_cred(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_stun_auth_cred_data_dyn_cred obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pj_stun_auth_cred_data_dyn_cred(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setUser_data(byte[] value) {
    pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_user_data_set(swigCPtr, this, value);
  }

  public byte[] getUser_data() {
	return pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_user_data_get(swigCPtr, this);
}

  public void setGet_auth(SWIGTYPE_p_f_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t__int value) {
    pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_auth_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t__int getGet_auth() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_auth_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t__int(cPtr, false);
  }

  public void setGet_cred(SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t_p_pj_str_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int value) {
    pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_cred_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t_p_pj_str_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t_p_pj_str_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int getGet_cred() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_cred_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_pj_pool_t_p_pj_str_t_p_pj_str_t_p_pj_str_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int(cPtr, false);
  }

  public void setGet_password(SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_pj_pool_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int value) {
    pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_password_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_pj_pool_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_pj_pool_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int getGet_password() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_get_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_pj_pool_t_p_enum_pj_stun_passwd_type_p_pj_str_t__int(cPtr, false);
  }

  public void setVerify_nonce(SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_q_const__pj_str_t__int value) {
    pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_verify_nonce_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_q_const__pj_str_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_q_const__pj_str_t__int getVerify_nonce() {
    long cPtr = pjsuaJNI.pj_stun_auth_cred_data_dyn_cred_verify_nonce_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__pj_stun_msg_p_void_p_q_const__pj_str_t_p_q_const__pj_str_t_p_q_const__pj_str_t__int(cPtr, false);
  }

  public pj_stun_auth_cred_data_dyn_cred() {
    this(pjsuaJNI.new_pj_stun_auth_cred_data_dyn_cred(), true);
  }

}
