/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_codec_fmtp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_codec_fmtp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_codec_fmtp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjmedia_codec_fmtp(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setCnt(short value) {
    pjsuaJNI.pjmedia_codec_fmtp_cnt_set(swigCPtr, this, value);
  }

  public short getCnt() {
    return pjsuaJNI.pjmedia_codec_fmtp_cnt_get(swigCPtr, this);
  }

  public pjmedia_codec_fmtp_param getParam() {
    long cPtr = pjsuaJNI.pjmedia_codec_fmtp_param_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjmedia_codec_fmtp_param(cPtr, false);
  }

  public pjmedia_codec_fmtp() {
    this(pjsuaJNI.new_pjmedia_codec_fmtp(), true);
  }

}
