/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_aud_dev_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_aud_dev_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_aud_dev_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjmedia_aud_dev_info(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(String value) {
    pjsuaJNI.pjmedia_aud_dev_info_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return pjsuaJNI.pjmedia_aud_dev_info_name_get(swigCPtr, this);
  }

  public void setInput_count(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_input_count_set(swigCPtr, this, value);
  }

  public long getInput_count() {
    return pjsuaJNI.pjmedia_aud_dev_info_input_count_get(swigCPtr, this);
  }

  public void setOutput_count(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_output_count_set(swigCPtr, this, value);
  }

  public long getOutput_count() {
    return pjsuaJNI.pjmedia_aud_dev_info_output_count_get(swigCPtr, this);
  }

  public void setDefault_samples_per_sec(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_default_samples_per_sec_set(swigCPtr, this, value);
  }

  public long getDefault_samples_per_sec() {
    return pjsuaJNI.pjmedia_aud_dev_info_default_samples_per_sec_get(swigCPtr, this);
  }

  public void setDriver(String value) {
    pjsuaJNI.pjmedia_aud_dev_info_driver_set(swigCPtr, this, value);
  }

  public String getDriver() {
    return pjsuaJNI.pjmedia_aud_dev_info_driver_get(swigCPtr, this);
  }

  public void setCaps(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_caps_set(swigCPtr, this, value);
  }

  public long getCaps() {
    return pjsuaJNI.pjmedia_aud_dev_info_caps_get(swigCPtr, this);
  }

  public void setRoutes(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_routes_set(swigCPtr, this, value);
  }

  public long getRoutes() {
    return pjsuaJNI.pjmedia_aud_dev_info_routes_get(swigCPtr, this);
  }

  public void setExt_fmt_cnt(long value) {
    pjsuaJNI.pjmedia_aud_dev_info_ext_fmt_cnt_set(swigCPtr, this, value);
  }

  public long getExt_fmt_cnt() {
    return pjsuaJNI.pjmedia_aud_dev_info_ext_fmt_cnt_get(swigCPtr, this);
  }

  public void setExt_fmt(SWIGTYPE_p_pjmedia_format value) {
    pjsuaJNI.pjmedia_aud_dev_info_ext_fmt_set(swigCPtr, this, SWIGTYPE_p_pjmedia_format.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_format getExt_fmt() {
    long cPtr = pjsuaJNI.pjmedia_aud_dev_info_ext_fmt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjmedia_format(cPtr, false);
  }

  public pjmedia_aud_dev_info() {
    this(pjsuaJNI.new_pjmedia_aud_dev_info(), true);
  }

}
