# $Id: Makefile 5965 2009-08-17 14:57:56Z ironmissy $
#
# Digest Authentication - AAA generic support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth_aaa.so
DEFS+=-I$(LOCALBASE)/include
LIBS=

include ../../Makefile.modules
