# $Id: Makefile 5894 2009-07-20 13:04:45Z bogdan_iancu $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbexample.so
LIBS=

include ../../Makefile.modules
