# $Id: Makefile 5896 2009-07-20 14:37:03Z bogdan_iancu $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=tm.so
LIBS=

include ../../Makefile.modules
